#pragma once
#include "lib/types.h"
#include <SDL.h>

#define OX_GAMEPAD_MAX 4

typedef enum
{
    OX_GAMEPAD_1,
    OX_GAMEPAD_2,
    OX_GAMEPAD_3,
    OX_GAMEPAD_4,
} OX_GAMEPAD_ID;

typedef enum
{
    OX_GAMEPAD_BTN_A        = SDL_CONTROLLER_BUTTON_A,
    OX_GAMEPAD_BTN_B        = SDL_CONTROLLER_BUTTON_B,
    OX_GAMEPAD_BTN_X        = SDL_CONTROLLER_BUTTON_X,
    OX_GAMEPAD_BTN_Y        = SDL_CONTROLLER_BUTTON_Y,
    OX_GAMEPAD_BTN_BACK     = SDL_CONTROLLER_BUTTON_BACK,
    OX_GAMEPAD_BTN_START    = SDL_CONTROLLER_BUTTON_START,
    OX_GAMEPAD_BTN_WHITE    = SDL_CONTROLLER_BUTTON_LEFTSHOULDER,
    OX_GAMEPAD_BTN_BLACK    = SDL_CONTROLLER_BUTTON_RIGHTSHOULDER,
    OX_GAMEPAD_BTN_UP       = SDL_CONTROLLER_BUTTON_DPAD_UP,
    OX_GAMEPAD_BTN_DOWN     = SDL_CONTROLLER_BUTTON_DPAD_DOWN,
    OX_GAMEPAD_BTN_LEFT     = SDL_CONTROLLER_BUTTON_DPAD_LEFT,
    OX_GAMEPAD_BTN_RIGHT    = SDL_CONTROLLER_BUTTON_DPAD_RIGHT,
    OX_GAMEPAD_BTN_LSTICK   = SDL_CONTROLLER_BUTTON_LEFTSTICK,
    OX_GAMEPAD_BTN_RSTICK   = SDL_CONTROLLER_BUTTON_RIGHTSTICK,
} OX_GAMEPAD_BTN;

typedef enum
{
    OX_GAMEPAD_AXIS_LEFT_X      = SDL_CONTROLLER_AXIS_LEFTX,
    OX_GAMEPAD_AXIS_LEFT_Y      = SDL_CONTROLLER_AXIS_LEFTY,
    OX_GAMEPAD_AXIS_RIGHT_X     = SDL_CONTROLLER_AXIS_RIGHTX,
    OX_GAMEPAD_AXIS_RIGHT_Y     = SDL_CONTROLLER_AXIS_RIGHTY,
    OX_GAMEPAD_AXIS_LTRIGGER    = SDL_CONTROLLER_AXIS_TRIGGERLEFT,
    OX_GAMEPAD_AXIS_RTRIGGER    = SDL_CONTROLLER_AXIS_TRIGGERRIGHT,
} OX_GAMEPAD_AXIS;

void OX_InitInput();
void OX_HandleInputEvents(SDL_Event* e);
bool OX_RegisterGamepad(SDL_GameController* gc);
bool OX_UnregisterGamepad(SDL_GameController* gc);

bool OX_GetGamepadButton(OX_GAMEPAD_ID gamepad_id, OX_GAMEPAD_BTN btn);
int  OX_GetGamepadAxis(OX_GAMEPAD_ID gamepad_id, OX_GAMEPAD_AXIS axis);

SDL_GameController* OX_GetGamepad(OX_GAMEPAD_ID gamepad_id);